version: '3'
services: 
  nest:
    image: node:20.11.1
    container_name: nest-poc
    volumes:
      - ./nest/:/home/node/project
    environment:
      npm_config_cache: /home/node/cache
    working_dir: /home/node/project
    user: 1000:1000
    command: bash -c "npm install && npm run start"
    ports:
      - 3000:3000

  vue:
    image: node:20.11.1
    container_name: vue-poc
    volumes:
      - ./vue/:/home/node/project
    environment:
      npm_config_cache: /home/node/cache
    working_dir: /home/node/project
    user: 1000:1000
    command: bash -c "npm install && npm run dev"
    ports:
      - 5173:5173